from dataclasses import dataclass, field
from typing import Dict, Set, Optional, Tuple, Any
from datetime import datetime


@dataclass(frozen=True)
class ExecutionContext:
    """Externally issued ExecutionContext carried by the Runtime."""

    tenant_id: str
    account_id: str
    project_id: str
    anny_instance_id: str
    runtime_id: str
    session_id: str
    actor_id: str
    operation_id: str
    execution_id: str
    generation: int
    issued_at: datetime
    expires_at: datetime

    workspace_id: Optional[str] = None
    capabilities: Set[str] = field(default_factory=set)

    # Authority metadata is supplied by the external issuer and is never
    # generated by Runtime.
    principal: Optional[str] = None
    issuer: Optional[str] = None
    audience: Optional[str] = None
    authorization_refs: Tuple[str, ...] = field(default_factory=tuple)
    policy_refs: Tuple[str, ...] = field(default_factory=tuple)
    evidence_correlation: Any = None
    signature: Dict[str, str] = field(default_factory=dict)

    def has_capability(self, capability: str) -> bool:
        return capability in self.capabilities

    def is_valid(self, current_time: datetime, current_generation: int) -> bool:
        """Local enforcement only: expiry and externally issued generation fence."""
        if self.generation != current_generation:
            return False
        if current_time > self.expires_at:
            return False
        if current_time < self.issued_at:
            return False
        return True
