from dataclasses import dataclass, field
from typing import Dict, Set, Optional, Tuple, Any
from datetime import datetime


@dataclass(frozen=True)
class ExecutionContext:
    """Externally issued ExecutionContext carried by the Runtime."""

    tenant_id: str
    account_id: str
    project_id: str
    anny_instance_id: str
    runtime_id: str
    session_id: str
    actor_id: str
    operation_id: str
    execution_id: str
    generation: int
    issued_at: datetime
    expires_at: datetime

    # Required by the external issuer wire contract; preserved for execution-time revalidation.
    context_id: Optional[str] = None
    workspace_id: Optional[str] = None
    capabilities: Set[str] = field(default_factory=set)

    # Authority metadata is supplied by the external issuer and is never
    # generated by Runtime.
    installation_id: Optional[str] = None
    principal: Optional[str] = None
    issuer: Optional[str] = None
    audience: Optional[str] = None
    authorization_refs: Tuple[str, ...] = field(default_factory=tuple)
    policy_refs: Tuple[str, ...] = field(default_factory=tuple)
    evidence_correlation: Any = None
    signature: Dict[str, str] = field(default_factory=dict)
    # Set only by the Runtime-side cryptographic verifier; default is fail-closed.
    verification_status: str = "UNVERIFIED"
    verification_reason: Optional[str] = None
    verified_at: Optional[datetime] = None

    def has_capability(self, capability: str) -> bool:
        return capability in self.capabilities

    def matches_external_generation(self, expected_external_generation: int) -> bool:
        """Compare only against another externally authoritative generation value."""
        return (
            isinstance(expected_external_generation, int)
            and expected_external_generation >= 1
            and self.generation == expected_external_generation
        )

    def is_valid(self, current_time: datetime) -> bool:
        """Validate temporal validity only; never compare against RuntimeGeneration."""
        if current_time > self.expires_at:
            return False
        if current_time < self.issued_at:
            return False
        return True
