from enum import Enum, auto

class ContinuityEventType(str, Enum):
    MISSION_CREATED = "MISSION_CREATED"
    MISSION_STARTED = "MISSION_STARTED"
    TASK_CREATED = "TASK_CREATED"
    TASK_STARTED = "TASK_STARTED"
    STEP_CREATED = "STEP_CREATED"
    STEP_STARTED = "STEP_STARTED"

    ACTION_STARTED = "ACTION_STARTED"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    ACTION_FAILED = "ACTION_FAILED"

    REPOSITORY_INSPECTED = "REPOSITORY_INSPECTED"
    REPOSITORY_MUTATED = "REPOSITORY_MUTATED"
    MUTATION_PREPARED = "MUTATION_PREPARED"
    MUTATION_FINALIZED = "MUTATION_FINALIZED"
    COMMIT_CREATED = "COMMIT_CREATED"

    TEST_STARTED = "TEST_STARTED"
    TEST_COMPLETED = "TEST_COMPLETED"

    EVIDENCE_CREATED = "EVIDENCE_CREATED"
    DECISION_RECORDED = "DECISION_RECORDED"

    STATE_CHANGED = "STATE_CHANGED"
    BLOCKER_CREATED = "BLOCKER_CREATED"
    BLOCKER_CLEARED = "BLOCKER_CLEARED"

    HANDOFF_CREATED = "HANDOFF_CREATED"
    HANDOFF_ACCEPTED = "HANDOFF_ACCEPTED"

    STEP_PAUSED = "STEP_PAUSED"
    STEP_RESUMED = "STEP_RESUMED"

    MISSION_BLOCKED = "MISSION_BLOCKED"
    MISSION_RESUMED = "MISSION_RESUMED"

    MISSION_VERIFIED = "MISSION_VERIFIED"
    MISSION_CERTIFIED = "MISSION_CERTIFIED"
    MISSION_SUPERSEDED = "MISSION_SUPERSEDED"
